name: webviewpizza
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.20
  webview_flutter: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  geolocator: ^10.0.0
  image_picker: ^0.8.7+5
  change_app_package_name: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# La configuración de flutter_launcher_icons debe estar aquí, completamente fuera de la sección "flutter":
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  # ... el resto de tu configuración de flutter como assets, fonts, etc.
